### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by msaroufim** [herpdederp/MachineLearningFramework#1]
Thanks a bunch for setting things up. Here are some suggestions for what to do next

- Create a function for each type of action - e.g: Turn right, Look up, Shoot, Walk forward etc

- Get rid of your update function so we can simulate the game at whatever speed we need

- Make the goal a trackable public variable - e.g: number of enemies killed and make sure it gets updated if an enemy gets killed

- Get world nearby world state - e.g: in the player class create a function that returns all relevant object types and their location around the player - can do this via a spherical raycast or projecting assuming a 1st person view. Honestly whatever is easiest for you to implement

**Comment by herpdederp** [comment]
Roger

**Comment by herpdederp** [comment]
Half done, still need to implement Move, Shoot, GetNearestEnemy, etc

**Comment by herpdederp** [comment]
This is pretty much done, API can be expanded a lot to get the state of the world, right now you can just get the direction of the nearest target.

**Comment by msaroufim** [comment]
Awesome, I'll start writing code directly in this repo
